# Generated by Django 3.0.8 on 2020-11-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_submission_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='time_taken',
        ),
    ]
